name: Terraform Destroy

on:
  workflow_dispatch: # Cho phép bạn bấm nút "Run workflow" thủ công

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.12.1 # Hoặc phiên bản bạn dùng

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        env:
          TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}
        run: terraform destroy -auto-approve
